### ISSUE TITLE
Replace maildev

### ISSUE THREAD

**Issue by groenroos** [saplingjs/sapling#420]
We use [`maildev`](https://github.com/maildev/maildev/) to test email capabilities in the `Notifications` lib.

However, the `maildev` package seems unmaintained, with multiple dependencies with security alerts, that have not been resolved or even acknowledged for over a year: maildev/maildev#352, maildev/maildev#356, maildev/maildev#359, maildev/maildev#362, maildev/maildev#374

While I don't think these security alerts will compromise using Sapling (as `maildev` is only a dev dependency for unit testing), I'm spending an outsize amount of time dealing with Dependabot security alerts and npm audits because of this.

Identify a suitable alternative for `maildev`, and refactor the `Notifications` test suite to eliminate the dependency.

**Comment by soulteary** [comment]
I agree with your views and opinions, because I also spent a long time sorting out and solving the problems in the old version of maildev. 

But frankly speaking, there is no good choice at present, it is better to build the maildev v2.x version together.

btw: I came across this pr by searching, recently maildev updated a new version, I recommend you to use the new version @groenroos

**Comment by groenroos** [comment]
@soulteary Thanks for reaching out, and for resurrecting maildev, it's great to see! ⭐️

I'm keen on upgrading to 2.x to avoid finding and implementing an alternative; however, it doesn't seem to be available on npm yet. Do you have an idea of when it will be?

**Comment by soulteary** [comment]
Don't mention it. @groenroos 

I will keep reminding the npm maintainers to update the project's packages as soon as possible, but we have time difference, so it may take a day or two...

**Comment by groenroos** [comment]
Alright - I (or at least Dependabot) will keep my eyes peeled! Thanks! 👍

**Comment by soulteary** [comment]
Hahaha I will sync your last situation
