### ISSUE TITLE
Potentially convert to tinyhttp

### ISSUE THREAD

**Issue by groenroos** [saplingjs/sapling#97]
[tinyhttp](https://github.com/talentlessguy/tinyhttp) seems to be a largely Express-compatible alternative Node.js server framework. Consider whether we should ditch Express for tinyhttp.

### Pros

* Twice as fast as Express
* Fully compatible with Express middleware, so theoretically migration shouldn't cause huge problems
* TypeScript

### Cons

* Not as battle-tested as Express
* Community is a lot smaller

### Open questions

* We need to ensure that all the other Express bits we use in fact work with tinyhttp (session with any arbitrary connect store, file upload, etc)
* As Sapling adds some overhead, need to benchmark both implementations to make sure the performance/speed benefit is still applicable - the cons are probably worth it if it's truly around 2x as fast, but perhaps not worth it as much if the speed improvement is incremental/negligible

**Comment by talentlessguy** [comment]
Hi, tinyhttp author here

recently I released 1.3 with lots of bugfixes and improvements. Community also has grown a bit but stll not as large.

**Comment by groenroos** [comment]
Nice one! I'll take a look at what it'll take to do this conversion over the next weekend, and see where we are! 👍
